name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:  
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: |
        cd src
        dotnet build -c Release -o out
        cd ..
        
    - name: Package Release
      run: |
        cd src
        dotnet pack -c Release -o out SharpRakLib.Core/SharpRakLib.Core.csproj
        cd ..
      
    - name: Push to NuGet
      run: |
        cd src
        dotnet nuget push out/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json
      env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
